# docker/configs/supervisord/supervisord.conf

[unix_http_server]
file=/run/supervisord.sock

[supervisord]
logfile=/var/log/supervisord/supervisord.log
loglevel=info
pidfile=/run/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
startsecs=1
priority=10
stdout_logfile=/var/log/supervisord/rsyslog.log
stderr_logfile=/var/log/supervisord/rsyslog.log

[program:postfix]
command=/usr/libexec/postfix/master -d
autostart=true
autorestart=true
priority=20
stderr_logfile=/var/log/supervisord/postfix.log
stdout_logfile=/var/log/supervisord/postfix.log
stopasgroup=true
killasgroup=true

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
startsecs=2
priority=30
stdout_logfile=/var/log/supervisord/dovecot.log
stderr_logfile=/var/log/supervisord/dovecot.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
stdout_logfile=/var/log/supervisord/nginx.log
stderr_logfile=/var/log/supervisord/nginx.log
priority=30

[program:php-fpm]
command=/usr/sbin/php-fpm83 --nodaemonize --fpm-config /etc/php83/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/php-fpm.log
stderr_logfile=/var/log/supervisord/php-fpm.log
priority=20

[program:mariadb]
command=/usr/bin/mariadbd --datadir=/var/lib/mysql
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/mariadb.log
stderr_logfile=/var/log/supervisord/mariadb.log
priority=10

[program:dnsmasq]
command=/usr/sbin/dnsmasq --no-daemon
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/dnsmasq.log
stderr_logfile=/var/log/supervisord/dnsmasq.log
priority=10

[program:rspamd]
command=/usr/bin/rspamd -f
user=rspamd
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisord/supervisord-rspamd.log
stdout_logfile=/var/log/supervisord/supervisord-rspamd.log


[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
autostart=true
autorestart=true
startsecs=3
priority=20
stdout_logfile=/var/log/supervisord/supervisord-redis.log
stderr_logfile=/var/log/supervisord/supervisord-redis.log

[program:n8n]
command=/usr/bin/env -i HOME="/home/n8n" PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" N8N_USER_FOLDER="/home/n8n/.n8n" N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS="true" N8N_PORT="5678" N8N_HOST="0.0.0.0" N8N_PROTOCOL="http" N8N_EDITOR_BASE_URL="%(ENV_N8N_EDITOR_BASE_URL)s" N8N_RUNNERS_ENABLED="true" N8N_RUNNERS_WORKER_COUNT="4" N8N_JWT_SECRET="%(ENV_N8N_JWT_SECRET)s" DB_SQLITE_POOL_SIZE="5" N8N_DEFAULT_BINARY_DATA_MODE="filesystem" N8N_DIAGNOSTICS_ENABLED="false" N8N_VERSION_NOTIFICATIONS_ENABLED="false" N8N_TEMPLATES_ENABLED="false" EXTERNAL_FRONTEND_HOOKS_URLS="" N8N_DIAGNOSTICS_CONFIG_FRONTEND="" N8N_DIAGNOSTICS_CONFIG_BACKEND="" IWB_STORJ_WPOPS_BUCKET="%(ENV_IWB_STORJ_WPOPS_BUCKET)s" IWB_DOMAIN="%(ENV_IWB_DOMAIN)s" COMPOSE_PROJECT_NAME="%(ENV_COMPOSE_PROJECT_NAME)s" NODES_INCLUDE="[\"n8n-nodes-base.executeCommand\"]" n8n start
directory=/home/n8n
user=n8n
autostart=true
autorestart=true
startsecs=5
priority=50
stderr_logfile=/var/log/supervisord/n8n.log
stdout_logfile=/var/log/supervisord/n8n.log


[program:cron]
command=/usr/sbin/crond -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/cron.log
stderr_logfile=/var/log/supervisord/cron.log

