# docker/configs/supervisord/supervisord.conf

[unix_http_server]
file=/run/supervisord.sock

[supervisord]
logfile=/var/log/supervisord.log
loglevel=info
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
startsecs=1
priority=10
stdout_logfile=/var/log/rsyslog.stdout.log
stderr_logfile=/var/log/rsyslog.stderr.log

[program:postfix]
command=/usr/libexec/postfix/master -d
autostart=true
autorestart=true
priority=20
stderr_logfile=/var/log/postfix.stderr.log
stdout_logfile=/var/log/postfix.stdout.log
stopasgroup=true
killasgroup=true

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
startsecs=2
priority=30
stdout_logfile=/var/log/dovecot.stdout.log
stderr_logfile=/var/log/dovecot.stderr.log
