# docker/configs/supervisord/supervisord.conf

[unix_http_server]
file=/run/supervisord.sock

[supervisord]
logfile=/var/log/supervisord/supervisord.log
loglevel=info
pidfile=/run/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
startsecs=1
priority=10
stdout_logfile=/var/log/supervisord/rsyslog.log
stderr_logfile=/var/log/supervisord/rsyslog.log

[program:postfix]
command=/usr/libexec/postfix/master -d
autostart=true
autorestart=true
priority=20
stderr_logfile=/var/log/supervisord/postfix.log
stdout_logfile=/var/log/supervisord/postfix.log
stopasgroup=true
killasgroup=true

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
startsecs=2
priority=30
stdout_logfile=/var/log/supervisord/dovecot.log
stderr_logfile=/var/log/supervisord/dovecot.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
stdout_logfile=/var/log/supervisord/nginx.log
stderr_logfile=/var/log/supervisord/nginx.log
priority=30

[program:php-fpm]
command=/usr/sbin/php-fpm83 --nodaemonize --fpm-config /etc/php83/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/php-fpm.log
stderr_logfile=/var/log/supervisord/php-fpm.log
priority=20

[program:mariadb]
command=/usr/bin/mariadbd --datadir=/var/lib/mysql
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/mariadb.log
stderr_logfile=/var/log/supervisord/mariadb.log
priority=10

[program:dnsmasq]
command=/usr/sbin/dnsmasq --no-daemon
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/dnsmasq.log
stderr_logfile=/var/log/supervisord/dnsmasq.log
priority=10

[program:rspamd]
command=/usr/bin/rspamd -f
user=rspamd
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisord/supervisord-rspamd.log
stdout_logfile=/var/log/supervisord/supervisord-rspamd.log


[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
autostart=true
autorestart=true
startsecs=3
priority=20
stdout_logfile=/var/log/supervisord/supervisord-redis.log
stderr_logfile=/var/log/supervisord/supervisord-redis.log

[program:n8n]
command=/usr/bin/env n8n
directory=/root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisord/n8n.log
stdout_logfile=/var/log/supervisord/n8n.log


[program:cron]
command=/usr/sbin/crond -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/cron.log
stderr_logfile=/var/log/supervisord/cron.log

