upload_max_filesize = 350M
post_max_size = 350M
memory_limit = 512M
max_execution_time = 120

; Enable commonly needed PHP extensions
# extension=exif.so
# extension=iconv.so
# extension=zip.so
# extension=imagick.so
# extension=gmp.so
# extension=bcmath.so
